##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.ksqldb_server:0.9.0 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/usr/bin/docker/run"
# config omitted for the moment
# COPY ./conteco/ksql_server/base/* /etc/ksql/
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="ksqldb_server" \
    CONTECO_NAME="tocloud" \
    CONTECO_TAG="0.9.0" \
    CONTECO_BASE="external.ksqldb_server:0.9.0" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="ksqldb_server" \
      io.vcweb.name="tocloud" \
      io.vcweb.tag="0.9.0" \
      io.vcweb.base="external.ksqldb_server:0.9.0" \
      io.vcweb.build="image-base" \
      io.vcweb.label="ksqldb_server.tocloud - Conteco " \
      io.vcweb.description="Confluent ksqlDB Server to cloud image, using default configuration." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.ksqldb_server.tocloud --help"
##### END image.base/Dockerfile/env-labels-footer #####
