##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="ksqldb_server" \
    CONTECO_NAME="sasl" \
    CONTECO_TAG="0.12.0" \
    CONTECO_BASE="controlplane.base" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="ksqldb_server" \
      io.vcweb.name="sasl" \
      io.vcweb.tag="0.12.0" \
      io.vcweb.base="controlplane.base" \
      io.vcweb.build="image-base" \
      io.vcweb.label="ksqldb_server.sasl - Conteco " \
      io.vcweb.description="Confluent ksqlDB Server image, using SASL authentication." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.ksqldb_server.sasl --help"
##### END image.base/Dockerfile/env-labels-footer #####
