#!/usr/bin/env bash

export CONTECO_LABEL="ksqldb_server.sasl - Conteco "
export CONTECO_DESCRIPTION="Confluent ksqlDB Server image, using SASL authentication."

export CONTECO_TYPE="ksqldb_server"
export CONTECO_NAME="sasl"
export CONTECO_TAG="0.12.0"

export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="confluentinc/ksqldb-server:0.12.0"
