#!/usr/bin/env bash

export CONTECO_LABEL="ksqldb_server.tocloud - Conteco "
export CONTECO_DESCRIPTION="Confluent ksqlDB Server to cloud image, using default configuration."

export CONTECO_TYPE="ksqldb_server"
export CONTECO_NAME="tocloud"
export CONTECO_TAG="0.9.0"

export CONTECO_BASE="external.ksqldb_server:0.9.0"
export CONTECO_BUILD="image-base"
